eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6401/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/main/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth
        - id: eureka-server
          uri: http://localhost:6401
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:6401
          predicates:
            - Path=/eureka/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

server:
  port: 6402
