spring:
  application:
    name: eureka-server
  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 6401